/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/google": {
    /**
     * Valida el ID token de Google, verifica que el campo hd coincida con el
     * dominio corporativo configurado (GOOGLE_HOSTED_DOMAIN), crea o actualiza
     * el usuario por google_sub y retorna un JWT de acceso + refresh token opaco.
     */
    post: {
      parameters: {
        body: {
          /** Google ID token obtenido del cliente */
          body: definitions["dto.GoogleLoginRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.LoginResponse"];
        };
        /** body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** token invalido o dominio no autorizado */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** error interno */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/auth/logout": {
    /**
     * Revoca el refresh token si existe. Retorna 204 en todos los casos
     * (token inexistente, ya revocado, o revocado exitosamente).
     * No requiere JWT en el header.
     */
    post: {
      parameters: {
        body: {
          /** Refresh token a revocar */
          body?: definitions["dto.RefreshRequest"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/auth/refresh": {
    /**
     * Valida el refresh token presentado, detecta replay attacks (OWASP),
     * revoca el token anterior y emite un par nuevo (access + refresh).
     */
    post: {
      parameters: {
        body: {
          /** Refresh token actual */
          body: definitions["dto.RefreshRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.LoginResponse"];
        };
        /** body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** token invalido, expirado o reutilizado */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** error interno */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
}

export interface definitions {
  "dto.GoogleLoginRequest": {
    idToken: string;
  };
  "dto.LoginResponse": {
    access_token?: string;
    expires_at?: string;
    refresh_token?: string;
    user?: definitions["dto.UserDTO"];
  };
  "dto.RefreshRequest": {
    refreshToken: string;
  };
  "dto.UserDTO": {
    email?: string;
    id?: string;
    nombre?: string;
    roles?: string[];
  };
  "httperr.Error": {
    code?: string;
    details?: { [key: string]: string };
    message?: string;
  };
}

export interface operations {}

export interface external {}
