/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/google": {
    /**
     * Valida el ID token de Google, verifica que el campo hd coincida con el
     * dominio corporativo configurado (GOOGLE_HOSTED_DOMAIN), crea o actualiza
     * el usuario por google_sub y retorna un JWT de acceso + refresh token opaco.
     */
    post: {
      parameters: {
        body: {
          /** Google ID token obtenido del cliente */
          body: definitions["dto.GoogleLoginRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.LoginResponse"];
        };
        /** body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** token invalido o dominio no autorizado */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** error interno */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/auth/logout": {
    /**
     * Revoca el refresh token si existe. Retorna 204 en todos los casos
     * (token inexistente, ya revocado, o revocado exitosamente).
     * No requiere JWT en el header.
     */
    post: {
      parameters: {
        body: {
          /** Refresh token a revocar */
          body?: definitions["dto.RefreshRequest"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/auth/refresh": {
    /**
     * Valida el refresh token presentado, detecta replay attacks (OWASP),
     * revoca el token anterior y emite un par nuevo (access + refresh).
     */
    post: {
      parameters: {
        body: {
          /** Refresh token actual */
          body: definitions["dto.RefreshRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.LoginResponse"];
        };
        /** body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** token invalido, expirado o reutilizado */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** error interno */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses": {
    /** Retorna una pagina de cursos del caller. ?creator=me es obligatorio. */
    get: {
      parameters: {
        query: {
          /** Debe ser 'me' (solo cursos propios) */
          creator: string;
          /** Pagina (default 1) */
          page?: number;
          /** Tamano de pagina (max 100, default 20) */
          size?: number;
        };
      };
      responses: {
        /** pagina de cursos (items, page, size, total, totalPages) */
        200: {
          schema: { [key: string]: unknown };
        };
        /** creator debe ser 'me' */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** rol creador requerido */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    /** Crea un nuevo curso con estado=borrador. El creadorID viene del JWT. */
    post: {
      parameters: {
        body: {
          /** Datos del curso */
          body: definitions["dto.CreateCourseRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.CourseDetail"];
        };
        /** titulo faltante o invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** rol creador requerido */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{courseId}/evaluation": {
    /** Crea una evaluacion (1-1 por curso). El curso debe estar en borrador o rechazado. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          courseId: string;
        };
        body: {
          /** Datos de la evaluacion */
          body: definitions["dto.EvaluationCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.EvaluationResponse"];
        };
        /** body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** no es propietario del curso */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** ya existe evaluacion o curso no editable */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{courseId}/materials": {
    /** Persiste el material tras un PUT presignado exitoso. Re-valida tamano y MIME. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          courseId: string;
        };
        body: {
          /** Datos del material confirmado */
          body: definitions["dto.MaterialConfirmRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.MaterialResponse"];
        };
        /** clave de objeto invalida o campos faltantes */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** no es propietario del curso */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** estado no permite edicion */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** archivo demasiado grande */
        413: {
          schema: definitions["httperr.Error"];
        };
        /** tipo de contenido no permitido */
        415: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{courseId}/materials/presign": {
    /** Genera una URL PUT presignada para que el browser suba el archivo directamente a MinIO. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          courseId: string;
        };
        body: {
          /** Datos del archivo a subir */
          body: definitions["dto.MaterialPresignRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.PresignResponse"];
        };
        /** body invalido o campos faltantes */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** no es propietario del curso */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** estado no permite edicion */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** archivo demasiado grande */
        413: {
          schema: definitions["httperr.Error"];
        };
        /** tipo de contenido no permitido */
        415: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{courseId}/sections": {
    /** Crea una seccion. El curso debe estar en borrador o rechazado y pertenecer al caller. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          courseId: string;
        };
        body: {
          /** Datos de la seccion */
          body: definitions["dto.SectionCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.SectionResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** no es propietario del curso */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** estado no permite edicion */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{id}": {
    /** Retorna el detalle de un curso. Solo el creador propietario puede verlo. */
    get: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CourseDetail"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** rol creador requerido */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado o no pertenece al caller */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    /** Actualiza titulo y/o descripcion de un curso. Solo borrador o rechazado. */
    patch: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
        body: {
          /** Campos a actualizar (parcial) */
          body: definitions["dto.UpdateCourseRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CourseDetail"];
        };
        /** body invalido o sin campos */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** no es propietario del curso */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** estado no permite edicion */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{id}/evaluation": {
    /** Retorna la evaluacion con sus preguntas y opciones. Solo el propietario del curso. */
    get: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.EvaluationDetail"];
        };
        /** evaluacion o curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{id}/materials": {
    /** Retorna todos los materiales del curso ordenados por fecha de creacion ASC. Solo el propietario. */
    get: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.MaterialResponse"][];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** rol creador requerido */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado o no pertenece al caller */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{id}/materials/{materialId}/download": {
    /** Retorna una URL GET presignada con TTL = PresignTTL. Solo el propietario del curso. */
    get: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
          /** UUID del material */
          materialId: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.DownloadResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** material o curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{id}/sections": {
    /** Retorna el arbol de contenido del curso: secciones ordenadas por orden, */
    get: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SectionWithVideosResponse"][];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** rol creador requerido */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado o no pertenece al caller */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{id}/sections/reorder": {
    /** Actualiza el orden de las secciones. ids debe ser el conjunto exacto de secciones del curso. */
    patch: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
        body: {
          /** IDs en el nuevo orden */
          body: definitions["dto.ReorderRequest"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
        /** IDs invalidos o incompletos */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/evaluations/{id}": {
    /** Actualiza notaMinima y/o intentosMax. El curso debe estar en borrador o rechazado. */
    patch: {
      parameters: {
        path: {
          /** UUID de la evaluacion */
          id: string;
        };
        body: {
          /** Campos a actualizar */
          body: definitions["dto.EvaluationUpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.EvaluationResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/evaluations/{id}/questions": {
    /** Para verdadero_falso auto-crea 2 opciones. Para opcion_multiple empieza vacia. */
    post: {
      parameters: {
        path: {
          /** UUID de la evaluacion */
          id: string;
        };
        body: {
          /** Datos de la pregunta */
          body: definitions["dto.QuestionCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.QuestionDetail"];
        };
        /** tipo invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/materials/{id}": {
    /** Elimina la fila de material y hace un best-effort delete del objeto en storage. */
    delete: {
      parameters: {
        path: {
          /** UUID del material */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** no es propietario del curso */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** material no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/options/{id}": {
    delete: {
      parameters: {
        path: {
          /** UUID de la opcion */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        path: {
          /** UUID de la opcion */
          id: string;
        };
        body: {
          /** Campos a actualizar */
          body: definitions["dto.OptionUpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.OptionResponse"];
        };
      };
    };
  };
  "/questions/{id}": {
    delete: {
      parameters: {
        path: {
          /** UUID de la pregunta */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    patch: {
      parameters: {
        path: {
          /** UUID de la pregunta */
          id: string;
        };
        body: {
          /** Campos a actualizar */
          body: definitions["dto.QuestionUpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.QuestionResponse"];
        };
      };
    };
  };
  "/questions/{id}/options": {
    post: {
      parameters: {
        path: {
          /** UUID de la pregunta */
          id: string;
        };
        body: {
          /** Datos de la opcion */
          body: definitions["dto.OptionCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.OptionResponse"];
        };
        /** tipo incorrecto (verdadero_falso no permite agregar opciones) */
        400: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/sections/{id}": {
    /** Elimina la seccion y todos sus videos. Requiere ser propietario. */
    delete: {
      parameters: {
        path: {
          /** UUID de la seccion */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    /** Actualiza titulo de una seccion. Requiere ser propietario del curso. */
    patch: {
      parameters: {
        path: {
          /** UUID de la seccion */
          id: string;
        };
        body: {
          /** Campos a actualizar */
          body: definitions["dto.SectionUpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SectionResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** seccion no encontrada */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/sections/{sectionId}/videos": {
    /** Crea un video. La seccion y el curso deben pertenecer al caller. URL y proveedor se validan cruzadamente. */
    post: {
      parameters: {
        path: {
          /** UUID de la seccion */
          sectionId: string;
        };
        body: {
          /** Datos del video */
          body: definitions["dto.VideoCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.VideoResponse"];
        };
        /** url/proveedor invalidos */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/supervisions": {
    /** Retorna todas las relaciones supervisor-empleado. Solo administradores. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SupervisionItem"][];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    /** Asigna un supervisor a un empleado. Solo administradores. */
    post: {
      parameters: {
        body: {
          /** Relacion supervisor-empleado */
          body: definitions["dto.SupervisionCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.SupervisionItem"];
        };
        /** auto-supervision o body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** usuario no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** empleado ya tiene supervisor */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/supervisions/{id}": {
    /** Elimina la relacion por su ID. Solo administradores. */
    delete: {
      parameters: {
        path: {
          /** UUID de la relacion de supervision */
          id: string;
        };
      };
      responses: {
        /** Sin contenido */
        204: never;
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** relacion no encontrada */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/users": {
    /** Retorna una pagina de usuarios. Solo administradores. */
    get: {
      parameters: {
        query: {
          /** Pagina (default 1) */
          page?: number;
          /** Tamano de pagina (max 100, default 20) */
          size?: number;
          /** Busqueda por nombre o email (ILIKE) */
          q?: string;
          /** Filtro por rol exacto (alumno|creador|supervisor|administrador) */
          role?: string;
          /** Filtro por estado activo */
          active?: boolean;
        };
      };
      responses: {
        /** pagina de usuarios (items, page, size, total, totalPages) */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/users/me": {
    /** Retorna el detalle del usuario que realiza la peticion. Requiere JWT. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserDetail"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/users/{id}": {
    /** Retorna el detalle de un usuario. Solo administradores. */
    get: {
      parameters: {
        path: {
          /** UUID del usuario */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserDetail"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/users/{id}/active": {
    /** Establece el flag activo del usuario. Solo administradores. */
    patch: {
      parameters: {
        path: {
          /** UUID del usuario */
          id: string;
        };
        body: {
          /** Estado activo */
          body: definitions["dto.ActivePatchRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserDetail"];
        };
        /** body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** ultimo administrador activo */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/users/{id}/roles": {
    /** Aplica un delta de roles (add/remove). Solo administradores. */
    patch: {
      parameters: {
        path: {
          /** UUID del usuario */
          id: string;
        };
        body: {
          /** Delta de roles */
          body: definitions["dto.RolesPatchRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserDetail"];
        };
        /** rol invalido, conflicto add/remove, o body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** ultimo administrador activo */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/videos/{id}": {
    /** Elimina un video. Requiere ser propietario del curso. */
    delete: {
      parameters: {
        path: {
          /** UUID del video */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    /** Actualiza campos de un video. Si url o proveedor cambia, se re-validan cruzadamente. */
    patch: {
      parameters: {
        path: {
          /** UUID del video */
          id: string;
        };
        body: {
          /** Campos a actualizar */
          body: definitions["dto.VideoUpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.VideoResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
}

export interface definitions {
  "dto.ActivePatchRequest": {
    active: boolean;
  };
  "dto.CourseDetail": {
    creadorId?: string;
    createdAt?: string;
    descripcion?: string;
    estado?: string;
    hasContent?: boolean;
    id?: string;
    titulo?: string;
    updatedAt?: string;
  };
  "dto.CreateCourseRequest": {
    descripcion?: string;
    titulo: string;
  };
  "dto.DownloadResponse": {
    expiresAt?: string;
    url?: string;
  };
  "dto.EvaluationCreateRequest": {
    intentosMax?: number;
    notaMinima?: number;
  };
  "dto.EvaluationDetail": {
    courseId?: string;
    id?: string;
    intentosMax?: number;
    notaMinima?: number;
    questions?: definitions["dto.QuestionDetail"][];
  };
  "dto.EvaluationResponse": {
    courseId?: string;
    createdAt?: string;
    id?: string;
    intentosMax?: number;
    notaMinima?: number;
  };
  "dto.EvaluationUpdateRequest": {
    intentosMax?: number;
    notaMinima?: number;
  };
  "dto.GoogleLoginRequest": {
    idToken: string;
  };
  "dto.LoginResponse": {
    access_token?: string;
    expires_at?: string;
    refresh_token?: string;
    user?: definitions["dto.UserDTO"];
  };
  "dto.MaterialConfirmRequest": {
    contentType: string;
    key: string;
    nombre: string;
    tamanoBytes: number;
  };
  "dto.MaterialPresignRequest": {
    contentType: string;
    nombre: string;
    tamanoBytes: number;
  };
  "dto.MaterialResponse": {
    createdAt?: string;
    id?: string;
    mimeType?: string;
    /** @description mapped from MaterialModel.Titulo */
    nombre?: string;
    tamanoBytes?: number;
  };
  "dto.OptionCreateRequest": {
    correcta?: boolean;
    texto: string;
  };
  "dto.OptionResponse": {
    correcta?: boolean;
    id?: string;
    orden?: number;
    questionId?: string;
    texto?: string;
  };
  "dto.OptionUpdateRequest": {
    correcta?: boolean;
    texto?: string;
  };
  "dto.PresignResponse": {
    expiresAt?: string;
    key?: string;
    uploadUrl?: string;
  };
  "dto.QuestionCreateRequest": {
    enunciado: string;
    puntaje?: number;
    /** @enum {string} */
    tipo: "opcion_multiple" | "verdadero_falso";
  };
  "dto.QuestionDetail": {
    enunciado?: string;
    evaluationId?: string;
    id?: string;
    options?: definitions["dto.OptionResponse"][];
    orden?: number;
    puntaje?: number;
    tipo?: string;
  };
  "dto.QuestionResponse": {
    enunciado?: string;
    evaluationId?: string;
    id?: string;
    orden?: number;
    puntaje?: number;
    tipo?: string;
  };
  "dto.QuestionUpdateRequest": {
    enunciado?: string;
    orden?: number;
    puntaje?: number;
  };
  "dto.RefreshRequest": {
    refreshToken: string;
  };
  "dto.ReorderRequest": {
    ids: string[];
  };
  "dto.RolesPatchRequest": {
    add: string[];
    remove: string[];
  };
  "dto.SectionCreateRequest": {
    titulo: string;
  };
  "dto.SectionResponse": {
    courseId?: string;
    createdAt?: string;
    id?: string;
    orden?: number;
    titulo?: string;
  };
  "dto.SectionUpdateRequest": {
    titulo?: string;
  };
  "dto.SectionWithVideosResponse": {
    courseId?: string;
    createdAt?: string;
    id?: string;
    orden?: number;
    titulo?: string;
    videos?: definitions["dto.VideoResponse"][];
  };
  "dto.SupervisionCreateRequest": {
    empleadoId: string;
    supervisorId: string;
  };
  "dto.SupervisionItem": {
    creadoEn?: string;
    empleadoId?: string;
    id?: string;
    supervisorId?: string;
  };
  "dto.UpdateCourseRequest": {
    descripcion?: string;
    titulo?: string;
  };
  "dto.UserDTO": {
    email?: string;
    id?: string;
    nombre?: string;
    roles?: string[];
  };
  "dto.UserDetail": {
    activo?: boolean;
    createdAt?: string;
    email?: string;
    id?: string;
    nombre?: string;
    roles?: string[];
    updatedAt?: string;
  };
  "dto.VideoCreateRequest": {
    duracionS?: number;
    /** @enum {string} */
    proveedor: "youtube" | "vimeo";
    titulo: string;
    url: string;
  };
  "dto.VideoResponse": {
    createdAt?: string;
    duracionS?: number;
    id?: string;
    orden?: number;
    proveedor?: string;
    sectionId?: string;
    titulo?: string;
    url?: string;
  };
  "dto.VideoUpdateRequest": {
    duracionS?: number;
    /** @enum {string} */
    proveedor?: "youtube" | "vimeo";
    titulo?: string;
    url?: string;
  };
  "httperr.Error": {
    code?: string;
    details?: { [key: string]: string };
    message?: string;
  };
}

export interface operations {}

export interface external {}
