/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/approvals/pending": {
    /** Retorna todos los cursos con estado=en_revision. Solo administradores. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.PendingItemDTO"][];
        };
        /** no es administrador */
        403: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/attempts/{id}": {
    /** Retorna el intento con sus preguntas (sin correcta) y las respuestas actuales del estudiante. */
    get: {
      parameters: {
        path: {
          /** UUID del intento */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.AttemptStateResponse"];
        };
        /** intento no encontrado o no pertenece al usuario */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/attempts/{id}/answers": {
    /** Registra o actualiza la respuesta del estudiante para una pregunta del intento. */
    post: {
      parameters: {
        path: {
          /** UUID del intento */
          id: string;
        };
        body: {
          /** Respuesta */
          body: definitions["dto.AnswerRequest"];
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** opcion o pregunta invalida */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** intento no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** intento ya finalizado */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/attempts/{id}/submit": {
    /** Cierra el intento, calcula el puntaje y retorna el resultado. */
    post: {
      parameters: {
        path: {
          /** UUID del intento */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SubmitResponse"];
        };
        /** intento no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** intento ya finalizado */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/auth/google": {
    /**
     * Valida el ID token de Google, verifica que el campo hd coincida con el
     * dominio corporativo configurado (GOOGLE_HOSTED_DOMAIN), crea o actualiza
     * el usuario por google_sub y retorna un JWT de acceso + refresh token opaco.
     */
    post: {
      parameters: {
        body: {
          /** Google ID token obtenido del cliente */
          body: definitions["dto.GoogleLoginRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.LoginResponse"];
        };
        /** body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** token invalido o dominio no autorizado */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** error interno */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/auth/logout": {
    /**
     * Revoca el refresh token si existe. Retorna 204 en todos los casos
     * (token inexistente, ya revocado, o revocado exitosamente).
     * No requiere JWT en el header.
     */
    post: {
      parameters: {
        body: {
          /** Refresh token a revocar */
          body?: definitions["dto.RefreshRequest"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/auth/refresh": {
    /**
     * Valida el refresh token presentado, detecta replay attacks (OWASP),
     * revoca el token anterior y emite un par nuevo (access + refresh).
     */
    post: {
      parameters: {
        body: {
          /** Refresh token actual */
          body: definitions["dto.RefreshRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.LoginResponse"];
        };
        /** body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** token invalido, expirado o reutilizado */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** error interno */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/auth/sessions/me": {
    /**
     * Retorna los refresh tokens activos (no revocados, no expirados) del caller,
     * ordenados por created_at DESC. ip y userAgent son informativos/forenses;
     * no se usan para controlar la autenticacion.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SessionResponse"][];
        };
        /** sin autenticacion */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** error interno */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/auth/sessions/{id}": {
    /**
     * Establece revoked_at en el refresh token indicado, siempre que pertenezca
     * al caller y no este ya revocado. Retorna 404 en cualquier caso que no sea
     * propiedad del caller (sin filtrar existencia para no dar info de otras sesiones).
     */
    delete: {
      parameters: {
        path: {
          /** UUID de la sesion (refresh_token.id) */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** sin autenticacion */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** sesion no encontrada o no pertenece al caller */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** error interno */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/badges/me": {
    /** Devuelve las insignias ganadas por el usuario autenticado. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.ListBadgesResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/badges/ranking": {
    /** Devuelve el top-10 de usuarios con más certificados. Excluye usuarios con 0 certificados. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.RankingResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/catalog": {
    /** Retorna una página de cursos con estado='aprobado'. Soporta ?page, ?size, ?q (ILIKE titulo), */
    get: {
      parameters: {
        query: {
          /** Página (default 1) */
          page?: number;
          /** Tamaño de página (max 100, default 20) */
          size?: number;
          /** Filtro ILIKE en titulo */
          q?: string;
          /** basico|intermedio|avanzado */
          nivel?: string;
          /** UUID(s) de categoría, repetible → semántica OR */
          categoria?: string[];
          /** recientes|titulo (default recientes) */
          sort?: string;
        };
      };
      responses: {
        /** Página de CatalogCourseCard (items, page, size, total, totalPages) */
        200: {
          schema: { [key: string]: unknown };
        };
        /** filtro inválido (nivel o sort fuera del allow-list) */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/catalog/{id}": {
    /** Retorna preview (enrolled=false) o árbol completo (enrolled=true) según inscripción. */
    get: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
      };
      responses: {
        /** enrolled — árbol completo */
        200: {
          schema: definitions["dto.CourseDetailAlumnoResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado o no aprobado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/catalog/{id}/enroll": {
    /** Crea una fila de enrollment. Idempotente: segunda llamada devuelve 200 sin duplicar. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.EnrollmentResponse"];
        };
        /** JWT requerido */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado o no aprobado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/categorias": {
    /** Returns all curated categories. JWT required; any authenticated role (no role gate). */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CategoriaResponse"][];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/certificates/me": {
    /** Devuelve los certificados del usuario autenticado, ordenados por emitidoEn DESC. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.ListCertificatesResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/certificates/{id}": {
    /** Devuelve el certificado si pertenece al usuario autenticado. 404 para no-propietarios (anti-enumeración). */
    get: {
      parameters: {
        path: {
          /** Certificate ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CertificateResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/certificates/{id}/download": {
    /** Devuelve una URL presignada para descargar el PDF del certificado. Requiere ser el propietario. */
    get: {
      parameters: {
        path: {
          /** Certificate ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.DownloadURLResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses": {
    /** Retorna una pagina de cursos del caller. ?creator=me es obligatorio. */
    get: {
      parameters: {
        query: {
          /** Debe ser 'me' (solo cursos propios) */
          creator: string;
          /** Pagina (default 1) */
          page?: number;
          /** Tamano de pagina (max 100, default 20) */
          size?: number;
        };
      };
      responses: {
        /** pagina de cursos (items, page, size, total, totalPages) */
        200: {
          schema: { [key: string]: unknown };
        };
        /** creator debe ser 'me' */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** rol creador requerido */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    /** Crea un nuevo curso con estado=borrador. El creadorID viene del JWT. */
    post: {
      parameters: {
        body: {
          /** Datos del curso */
          body: definitions["dto.CreateCourseRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.CourseDetail"];
        };
        /** titulo faltante o invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** rol creador requerido */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{courseId}/approve": {
    /** Aprueba un curso en revision. Crea fila de auditoria y actualiza estado a aprobado. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          courseId: string;
        };
        body: {
          /** Comentario opcional */
          body?: definitions["dto.ApproveRequest"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
        /** no es administrador */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** curso no en revision */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{courseId}/evaluation": {
    /** Crea una evaluacion (1-1 por curso). El curso debe estar en borrador o rechazado. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          courseId: string;
        };
        body: {
          /** Datos de la evaluacion */
          body: definitions["dto.EvaluationCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.EvaluationResponse"];
        };
        /** body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** no es propietario del curso */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** ya existe evaluacion o curso no editable */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{courseId}/reject": {
    /** Rechaza un curso en revision con un comentario obligatorio. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          courseId: string;
        };
        body: {
          /** Comentario requerido */
          body: definitions["dto.RejectRequest"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
        /** comentario requerido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** no es administrador */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** curso no en revision */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{courseId}/sections": {
    /** Crea una seccion. El curso debe estar en borrador o rechazado y pertenecer al caller. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          courseId: string;
        };
        body: {
          /** Datos de la seccion */
          body: definitions["dto.SectionCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.SectionResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** no es propietario del curso */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** estado no permite edicion */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{courseId}/submit": {
    /** Transiciona el curso de borrador/rechazado a en_revision. Valida propiedad, estado, contenido y evaluacion. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          courseId: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SubmitReviewResponse"];
        };
        /** request invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** no es propietario del curso */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** estado invalido / sin contenido / evaluacion incompleta */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{courseId}/thumbnail": {
    /** course-structure-v2: sets miniatura_key on the course. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          courseId: string;
        };
        body: {
          /** key de la miniatura */
          body: definitions["dto.ThumbnailConfirmRequest"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/courses/{courseId}/thumbnail/presign": {
    /** course-structure-v2: imagen MIME only. Owner-gated + editable gate. */
    post: {
      parameters: {
        path: {
          /** UUID del curso */
          courseId: string;
        };
        body: {
          /** Datos de la imagen */
          body: definitions["dto.MaterialPresignRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.PresignResponse"];
        };
      };
    };
  };
  "/courses/{id}": {
    /** Retorna el detalle de un curso. Solo el creador propietario puede verlo. */
    get: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CourseDetail"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** rol creador requerido */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado o no pertenece al caller */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    /** Actualiza titulo y/o descripcion de un curso. Solo borrador o rechazado. */
    patch: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
        body: {
          /** Campos a actualizar (parcial) */
          body: definitions["dto.UpdateCourseRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CourseDetail"];
        };
        /** body invalido o sin campos */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** no es propietario del curso */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** estado no permite edicion */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{id}/approvals": {
    /** Retorna las filas de aprobacion/rechazo de un curso. Accessible para el propietario o administrador. */
    get: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.ApprovalHistoryDTO"][];
        };
        /** no es propietario ni administrador */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{id}/evaluation": {
    /** Retorna la evaluacion con sus preguntas y opciones. Solo el propietario del curso. */
    get: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.EvaluationDetail"];
        };
        /** evaluacion o curso no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{id}/evaluation/summary": {
    /** Retorna el id, notaMinima e intentosMax de la evaluacion para un curso aprobado. */
    get: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.EvaluationSummaryResponse"];
        };
        /** sin autenticacion */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** curso o evaluacion no encontrada / curso no aprobado */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{id}/sections": {
    /** Retorna el arbol de contenido del curso: secciones ordenadas por orden, */
    get: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SectionWithVideosResponse"][];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** rol creador requerido */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** curso no encontrado o no pertenece al caller */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/courses/{id}/sections/reorder": {
    /** Actualiza el orden de las secciones. ids debe ser el conjunto exacto de secciones del curso. */
    patch: {
      parameters: {
        path: {
          /** UUID del curso */
          id: string;
        };
        body: {
          /** IDs en el nuevo orden */
          body: definitions["dto.ReorderRequest"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
        /** IDs invalidos o incompletos */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/evaluations/{id}": {
    /** Actualiza notaMinima y/o intentosMax. El curso debe estar en borrador o rechazado. */
    patch: {
      parameters: {
        path: {
          /** UUID de la evaluacion */
          id: string;
        };
        body: {
          /** Campos a actualizar */
          body: definitions["dto.EvaluationUpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.EvaluationResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/evaluations/{id}/attempts": {
    /** Crea un intento para el usuario autenticado en la evaluacion indicada. */
    post: {
      parameters: {
        path: {
          /** UUID de la evaluacion */
          id: string;
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.AttemptStartResponse"];
        };
        /** evaluacion no encontrada */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** intento abierto o maximo alcanzado */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/evaluations/{id}/questions": {
    /** Para verdadero_falso auto-crea 2 opciones. Para opcion_multiple empieza vacia. */
    post: {
      parameters: {
        path: {
          /** UUID de la evaluacion */
          id: string;
        };
        body: {
          /** Datos de la pregunta */
          body: definitions["dto.QuestionCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.QuestionDetail"];
        };
        /** tipo invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/materials/{id}": {
    /** Elimina la fila de material y hace un best-effort delete del objeto en storage. */
    delete: {
      parameters: {
        path: {
          /** UUID del material */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** no es propietario del curso */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** material no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/materials/{id}/download": {
    /** course-structure-v2: URL /materials/:id/download (flat; chain ownership via video). */
    get: {
      parameters: {
        path: {
          /** UUID del material */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.DownloadResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** not owner or not enrolled */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** material not found */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/notifications/me": {
    /** Devuelve las notificaciones del usuario autenticado, paginadas por creado_en DESC. */
    get: {
      parameters: {
        query: {
          /** Página (default 1) */
          page?: number;
          /** Tamaño (default 20) */
          size?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.NotificationListResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/notifications/me/read-all": {
    /** Marca todas las notificaciones del usuario autenticado como leídas. */
    patch: {
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: boolean };
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/notifications/me/unread-count": {
    /** Devuelve el número de notificaciones no leídas del usuario autenticado. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UnreadCountResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/notifications/{id}/read": {
    /** Marca una notificación específica como leída. Solo el propietario puede hacerlo. */
    patch: {
      parameters: {
        path: {
          /** Notification UUID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: boolean };
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/options/{id}": {
    delete: {
      parameters: {
        path: {
          /** UUID de la opcion */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        path: {
          /** UUID de la opcion */
          id: string;
        };
        body: {
          /** Campos a actualizar */
          body: definitions["dto.OptionUpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.OptionResponse"];
        };
      };
    };
  };
  "/questions/{id}": {
    delete: {
      parameters: {
        path: {
          /** UUID de la pregunta */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    patch: {
      parameters: {
        path: {
          /** UUID de la pregunta */
          id: string;
        };
        body: {
          /** Campos a actualizar */
          body: definitions["dto.QuestionUpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.QuestionResponse"];
        };
      };
    };
  };
  "/questions/{id}/options": {
    post: {
      parameters: {
        path: {
          /** UUID de la pregunta */
          id: string;
        };
        body: {
          /** Datos de la opcion */
          body: definitions["dto.OptionCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.OptionResponse"];
        };
        /** tipo incorrecto (verdadero_falso no permite agregar opciones) */
        400: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/reports/courses": {
    /** Retorna estadísticas por curso para todos los cursos. Solo administradores. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CourseReportItem"][];
        };
        /** sin autenticación */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** no es administrador */
        403: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/reports/global": {
    /** Retorna métricas agregadas del sistema. Solo administradores. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.GlobalReportResponse"];
        };
        /** sin autenticación */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** no es administrador */
        403: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/reports/team": {
    /** Retorna los empleados supervisados por el caller con sus métricas de progreso. Solo supervisors. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.TeamReportItem"][];
        };
        /** sin autenticación */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** no es supervisor */
        403: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/reports/users/{id}/progress": {
    /** Retorna las métricas de progreso de un usuario. Accesible para el propio usuario o un administrador. */
    get: {
      parameters: {
        path: {
          /** UUID del usuario */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserProgressResponse"];
        };
        /** sin autenticación */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** no es el usuario ni administrador */
        403: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/sections/{id}": {
    /** Elimina la seccion y todos sus videos. Requiere ser propietario. */
    delete: {
      parameters: {
        path: {
          /** UUID de la seccion */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    /** Actualiza titulo de una seccion. Requiere ser propietario del curso. */
    patch: {
      parameters: {
        path: {
          /** UUID de la seccion */
          id: string;
        };
        body: {
          /** Campos a actualizar */
          body: definitions["dto.SectionUpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SectionResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** seccion no encontrada */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/sections/{sectionId}/videos": {
    /** Crea un video. La seccion y el curso deben pertenecer al caller. URL y proveedor se validan cruzadamente. */
    post: {
      parameters: {
        path: {
          /** UUID de la seccion */
          sectionId: string;
        };
        body: {
          /** Datos del video */
          body: definitions["dto.VideoCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.VideoResponse"];
        };
        /** url/proveedor invalidos */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/supervisions": {
    /** Retorna todas las relaciones supervisor-empleado. Solo administradores. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SupervisionItem"][];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    /** Asigna un supervisor a un empleado. Solo administradores. */
    post: {
      parameters: {
        body: {
          /** Relacion supervisor-empleado */
          body: definitions["dto.SupervisionCreateRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.SupervisionItem"];
        };
        /** auto-supervision o body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** usuario no encontrado */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** empleado ya tiene supervisor */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/supervisions/{id}": {
    /** Elimina la relacion por su ID. Solo administradores. */
    delete: {
      parameters: {
        path: {
          /** UUID de la relacion de supervision */
          id: string;
        };
      };
      responses: {
        /** Sin contenido */
        204: never;
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** relacion no encontrada */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/users": {
    /** Retorna una pagina de usuarios. Solo administradores. */
    get: {
      parameters: {
        query: {
          /** Pagina (default 1) */
          page?: number;
          /** Tamano de pagina (max 100, default 20) */
          size?: number;
          /** Busqueda por nombre o email (ILIKE) */
          q?: string;
          /** Filtro por rol exacto (alumno|creador|supervisor|administrador) */
          role?: string;
          /** Filtro por estado activo */
          active?: boolean;
        };
      };
      responses: {
        /** pagina de usuarios (items, page, size, total, totalPages) */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/users/me": {
    /** Retorna el detalle del usuario que realiza la peticion. Requiere JWT. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserDetail"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/users/me/courses": {
    /** Retorna los enrollments del caller con titulo, creadorNombre, completado, inscritoEn. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.MyCourseItem"][];
        };
        /** JWT requerido */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/users/{id}": {
    /** Retorna el detalle de un usuario. Solo administradores. */
    get: {
      parameters: {
        path: {
          /** UUID del usuario */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserDetail"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/users/{id}/active": {
    /** Establece el flag activo del usuario. Solo administradores. */
    patch: {
      parameters: {
        path: {
          /** UUID del usuario */
          id: string;
        };
        body: {
          /** Estado activo */
          body: definitions["dto.ActivePatchRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserDetail"];
        };
        /** body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** ultimo administrador activo */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/users/{id}/roles": {
    /** Aplica un delta de roles (add/remove). Solo administradores. */
    patch: {
      parameters: {
        path: {
          /** UUID del usuario */
          id: string;
        };
        body: {
          /** Delta de roles */
          body: definitions["dto.RolesPatchRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserDetail"];
        };
        /** rol invalido, conflicto add/remove, o body invalido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** ultimo administrador activo */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/videos/{id}": {
    /** Elimina un video. Requiere ser propietario del curso. */
    delete: {
      parameters: {
        path: {
          /** UUID del video */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    /** Actualiza campos de un video. Si url o proveedor cambia, se re-validan cruzadamente. */
    patch: {
      parameters: {
        path: {
          /** UUID del video */
          id: string;
        };
        body: {
          /** Campos a actualizar */
          body: definitions["dto.VideoUpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.VideoResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/videos/{id}/materials": {
    /** course-structure-v2: URL /videos/:id/materials (videoID). */
    get: {
      parameters: {
        path: {
          /** UUID del video */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.MaterialResponse"][];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
      };
    };
    /** course-structure-v2: URL ahora bajo /videos/:id/materials (videoID). */
    post: {
      parameters: {
        path: {
          /** UUID del video */
          id: string;
        };
        body: {
          /** Datos del material confirmado */
          body: definitions["dto.MaterialConfirmRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.MaterialResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** Request Entity Too Large */
        413: {
          schema: definitions["httperr.Error"];
        };
        /** Unsupported Media Type */
        415: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/videos/{id}/materials/presign": {
    /** course-structure-v2: URL ahora bajo /videos/:id/materials/presign (videoID). */
    post: {
      parameters: {
        path: {
          /** UUID del video */
          id: string;
        };
        body: {
          /** Datos del archivo a subir */
          body: definitions["dto.MaterialPresignRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.PresignResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** Forbidden */
        403: {
          schema: definitions["httperr.Error"];
        };
        /** Not Found */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["httperr.Error"];
        };
        /** Request Entity Too Large */
        413: {
          schema: definitions["httperr.Error"];
        };
        /** Unsupported Media Type */
        415: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
  "/videos/{id}/progress": {
    /** PUT /api/videos/:id/progress — upsert caller-scoped video progress. */
    put: {
      parameters: {
        path: {
          /** UUID del video */
          id: string;
        };
        body: {
          /** Progreso del video */
          body: definitions["dto.VideoProgressRequest"];
        };
      };
      responses: {
        /** sin contenido — progreso registrado */
        204: never;
        /** cuerpo inválido */
        400: {
          schema: definitions["httperr.Error"];
        };
        /** JWT requerido */
        401: {
          schema: definitions["httperr.Error"];
        };
        /** video no encontrado o no inscrito (no-leak) */
        404: {
          schema: definitions["httperr.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httperr.Error"];
        };
      };
    };
  };
}

export interface definitions {
  "dto.ActivePatchRequest": {
    active: boolean;
  };
  "dto.AnswerRequest": {
    optionId: string;
    questionId: string;
  };
  "dto.ApprovalHistoryDTO": {
    adminId?: string;
    comentario?: string;
    id?: string;
    resueltoEn?: string;
    resultado?: string;
  };
  "dto.ApproveRequest": {
    comentario?: string;
  };
  "dto.AttemptAnswerView": {
    optionId?: string;
    questionId?: string;
  };
  "dto.AttemptStartResponse": {
    attemptId?: string;
    iniciadoEn?: string;
    numero?: number;
  };
  "dto.AttemptStateOptionResponse": {
    id?: string;
    texto?: string;
  };
  "dto.AttemptStateQuestionResponse": {
    enunciado?: string;
    id?: string;
    options?: definitions["dto.AttemptStateOptionResponse"][];
    puntaje?: number;
    tipo?: string;
  };
  "dto.AttemptStateResponse": {
    answers?: definitions["dto.AttemptAnswerView"][];
    aprobado?: boolean;
    attemptId?: string;
    numero?: number;
    puntaje?: number;
    questions?: definitions["dto.AttemptStateQuestionResponse"][];
    submitted?: boolean;
  };
  "dto.BadgeResponse": {
    /** @description Descripcion is the badge description. */
    descripcion?: string;
    /** @description ID is the badge UUID. */
    id?: string;
    /** @description Nombre is the badge display name. */
    nombre?: string;
    /** @description OtorgadoEn is the UTC timestamp when the badge was awarded. */
    otorgadoEn?: string;
  };
  "dto.CategoriaResponse": {
    id?: string;
    nombre?: string;
    slug?: string;
  };
  "dto.CertificateListItem": {
    /** @description Codigo is the unique verification code printed on the certificate. */
    codigo?: string;
    /** @description CourseID is the UUID of the course for which this cert was issued. */
    courseId?: string;
    /** @description CourseTitulo is the display title of the course (from courses seam). */
    courseTitulo?: string;
    /** @description EmitidoEn is the ISO-8601 timestamp when the certificate was issued. */
    emitidoEn?: string;
    /** @description ID is the certificate UUID. */
    id?: string;
  };
  "dto.CertificateResponse": {
    /** @description Codigo is the unique verification code. */
    codigo?: string;
    /** @description CourseID is the UUID of the course. */
    courseId?: string;
    /** @description CourseTitulo is the display title of the course. */
    courseTitulo?: string;
    /** @description EmitidoEn is the issue timestamp. */
    emitidoEn?: string;
    /** @description ID is the certificate UUID. */
    id?: string;
  };
  "dto.CourseDetail": {
    creadorId?: string;
    createdAt?: string;
    descripcion?: string;
    estado?: string;
    hasContent?: boolean;
    id?: string;
    titulo?: string;
    updatedAt?: string;
  };
  "dto.CourseDetailAlumnoResponse": {
    cantidadClases?: number;
    categorias?: definitions["dto.CategoriaResponse"][];
    creadorNombre?: string;
    descripcion?: string;
    /** @description always true */
    enrolled?: boolean;
    horasPractico?: number;
    horasVideo?: number;
    id?: string;
    miniaturaUrl?: string;
    nivel?: string;
    secciones?: definitions["dto.SectionWithVideosResponse"][];
    titulo?: string;
  };
  "dto.CoursePreviewResponse": {
    cantidadClases?: number;
    categorias?: definitions["dto.CategoriaResponse"][];
    creadorNombre?: string;
    descripcion?: string;
    /** @description always false */
    enrolled?: boolean;
    horasPractico?: number;
    horasVideo?: number;
    id?: string;
    miniaturaUrl?: string;
    nivel?: string;
    titulo?: string;
  };
  /** @description Per-course aggregate stats. */
  "dto.CourseReportItem": {
    /** @description range [0.0, 1.0]; frontend renders as % */
    approvalRate?: number;
    attempts?: number;
    courseId?: string;
    enrollments?: number;
    estado?: string;
    titulo?: string;
  };
  /** @description Course count by estado. */
  "dto.CoursesByEstadoItem": {
    estado?: string;
    total?: number;
  };
  "dto.CreateCourseRequest": {
    categoriaIds?: string[];
    descripcion?: string;
    horasPractico?: number;
    /** @enum {string} */
    nivel?: "basico" | "intermedio" | "avanzado";
    titulo: string;
  };
  "dto.DownloadResponse": {
    expiresAt?: string;
    url?: string;
  };
  "dto.DownloadURLResponse": {
    /** @description ExpiresAt is the UTC timestamp when the presigned URL expires. */
    expiresAt?: string;
    /** @description URL is the presigned GET URL for the certificate PDF. */
    url?: string;
  };
  "dto.EnrollmentResponse": {
    courseId?: string;
    /** @description always true on 200 */
    enrolled?: boolean;
  };
  "dto.EvaluationCreateRequest": {
    intentosMax?: number;
    notaMinima?: number;
  };
  "dto.EvaluationDetail": {
    courseId?: string;
    id?: string;
    intentosMax?: number;
    notaMinima?: number;
    questions?: definitions["dto.QuestionDetail"][];
  };
  "dto.EvaluationResponse": {
    courseId?: string;
    createdAt?: string;
    id?: string;
    intentosMax?: number;
    notaMinima?: number;
  };
  "dto.EvaluationSummaryResponse": {
    evaluationId?: string;
    intentosMax?: number;
    notaMinima?: number;
  };
  "dto.EvaluationUpdateRequest": {
    intentosMax?: number;
    notaMinima?: number;
  };
  /** @description System-wide aggregate metrics. */
  "dto.GlobalReportResponse": {
    activeUsers?: number;
    approvedCoursesPerMonth?: definitions["dto.MonthCountItem"][];
    certificatesIssued?: number;
    coursesByEstado?: definitions["dto.CoursesByEstadoItem"][];
    topCreators?: definitions["dto.TopCreatorItem"][];
    totalAttempts?: number;
    usersPerMonth?: definitions["dto.MonthCountItem"][];
  };
  "dto.GoogleLoginRequest": {
    idToken: string;
  };
  "dto.ListBadgesResponse": {
    badges?: definitions["dto.BadgeResponse"][];
  };
  "dto.ListCertificatesResponse": {
    certificates?: definitions["dto.CertificateListItem"][];
  };
  "dto.LoginResponse": {
    access_token?: string;
    expires_at?: string;
    refresh_token?: string;
    user?: definitions["dto.UserDTO"];
  };
  "dto.MaterialConfirmRequest": {
    contentType: string;
    key: string;
    nombre: string;
    tamanoBytes: number;
  };
  "dto.MaterialPresignRequest": {
    contentType: string;
    nombre: string;
    tamanoBytes: number;
  };
  "dto.MaterialResponse": {
    createdAt?: string;
    id?: string;
    mimeType?: string;
    /** @description mapped from MaterialModel.Titulo */
    nombre?: string;
    tamanoBytes?: number;
  };
  /** @description Month bucket with count. */
  "dto.MonthCountItem": {
    /** @description ISO "2006-01" */
    month?: string;
    total?: number;
  };
  "dto.MyCourseItem": {
    completado?: boolean;
    courseId?: string;
    creadorNombre?: string;
    inscritoEn?: string;
    titulo?: string;
  };
  "dto.NotificationListResponse": {
    items?: definitions["dto.NotificationResponse"][];
    page?: number;
    size?: number;
    total?: number;
    totalPages?: number;
  };
  "dto.NotificationResponse": {
    creadoEn?: string;
    cuerpo?: string;
    id?: string;
    leida?: boolean;
    refId?: string;
    tipo?: string;
    titulo?: string;
  };
  "dto.OptionCreateRequest": {
    correcta?: boolean;
    texto: string;
  };
  "dto.OptionResponse": {
    correcta?: boolean;
    id?: string;
    orden?: number;
    questionId?: string;
    texto?: string;
  };
  "dto.OptionUpdateRequest": {
    correcta?: boolean;
    texto?: string;
  };
  "dto.PendingItemDTO": {
    creadorId?: string;
    estado?: string;
    /** @description OQ-3: UpdatedAt would be ideal; using CreatedAt as proxy in C4.1 */
    fechaEnvio?: string;
    id?: string;
    titulo?: string;
  };
  "dto.PresignResponse": {
    expiresAt?: string;
    key?: string;
    uploadUrl?: string;
  };
  "dto.QuestionCreateRequest": {
    enunciado: string;
    puntaje?: number;
    /** @enum {string} */
    tipo: "opcion_multiple" | "verdadero_falso";
  };
  "dto.QuestionDetail": {
    enunciado?: string;
    evaluationId?: string;
    id?: string;
    options?: definitions["dto.OptionResponse"][];
    orden?: number;
    puntaje?: number;
    tipo?: string;
  };
  "dto.QuestionResponse": {
    enunciado?: string;
    evaluationId?: string;
    id?: string;
    orden?: number;
    puntaje?: number;
    tipo?: string;
  };
  "dto.QuestionUpdateRequest": {
    enunciado?: string;
    orden?: number;
    puntaje?: number;
  };
  "dto.RankingItem": {
    /** @description CertCount is the total number of certificates the user has earned. */
    certCount?: number;
    /** @description Posicion is the 1-based rank position. */
    posicion?: number;
    /** @description UserNombre is the display name of the ranked user. */
    userNombre?: string;
  };
  "dto.RankingResponse": {
    ranking?: definitions["dto.RankingItem"][];
  };
  "dto.RefreshRequest": {
    refreshToken: string;
  };
  "dto.RejectRequest": {
    comentario?: string;
  };
  "dto.ReorderRequest": {
    ids: string[];
  };
  "dto.RolesPatchRequest": {
    add: string[];
    remove: string[];
  };
  "dto.SectionCreateRequest": {
    titulo: string;
  };
  "dto.SectionResponse": {
    courseId?: string;
    createdAt?: string;
    id?: string;
    orden?: number;
    titulo?: string;
  };
  "dto.SectionUpdateRequest": {
    titulo?: string;
  };
  "dto.SectionWithVideosResponse": {
    courseId?: string;
    createdAt?: string;
    id?: string;
    orden?: number;
    titulo?: string;
    videos?: definitions["dto.VideoResponse"][];
  };
  /** @description Active session for the authenticated user. */
  "dto.SessionResponse": {
    /** @description CreatedAt is the token row creation timestamp (RFC3339). */
    createdAt?: string;
    /** @description ExpiresAt is the token expiry timestamp (RFC3339). */
    expiresAt?: string;
    /**
     * @description ID is the session (refresh token row) UUID.
     * @example 550e8400-e29b-41d4-a716-446655440000
     */
    id?: string;
    /**
     * @description IP is the client IP captured at token issuance. May be absent.
     * @example 10.0.0.1
     */
    ip?: string;
    /** @description UsedAt is the last rotation marker; null if this session has never been rotated. */
    usedAt?: string;
    /**
     * @description UserAgent is the HTTP User-Agent captured at token issuance. May be absent.
     * @example Mozilla/5.0
     */
    userAgent?: string;
  };
  "dto.SubmitResponse": {
    aprobado?: boolean;
    puntaje?: number;
  };
  "dto.SubmitReviewResponse": {
    courseId?: string;
    estado?: string;
  };
  "dto.SupervisionCreateRequest": {
    empleadoId: string;
    supervisorId: string;
  };
  "dto.SupervisionItem": {
    creadoEn?: string;
    empleadoId?: string;
    id?: string;
    supervisorId?: string;
  };
  /** @description Team member progress entry. */
  "dto.TeamReportItem": {
    completedCount?: number;
    empleadoId?: string;
    empleadoNombre?: string;
    enrolledCount?: number;
    lastAttemptDate?: string;
  };
  "dto.ThumbnailConfirmRequest": {
    key: string;
  };
  /** @description Creator ranked by aprobado course count. */
  "dto.TopCreatorItem": {
    nombre?: string;
    total?: number;
  };
  "dto.UnreadCountResponse": {
    unread?: number;
  };
  "dto.UpdateCourseRequest": {
    categoriaIds?: string[];
    descripcion?: string;
    horasPractico?: number;
    /** @enum {string} */
    nivel?: "basico" | "intermedio" | "avanzado";
    titulo?: string;
  };
  "dto.UserDTO": {
    email?: string;
    id?: string;
    nombre?: string;
    roles?: string[];
  };
  "dto.UserDetail": {
    activo?: boolean;
    createdAt?: string;
    email?: string;
    id?: string;
    nombre?: string;
    roles?: string[];
    updatedAt?: string;
  };
  /** @description User progress aggregate. */
  "dto.UserProgressResponse": {
    attemptsCount?: number;
    certificatesCount?: number;
    completedCount?: number;
    enrolledCount?: number;
    passedAttemptsCount?: number;
  };
  "dto.VideoCreateRequest": {
    descripcion?: string;
    duracionS?: number;
    /** @enum {string} */
    proveedor: "youtube" | "vimeo";
    titulo: string;
    url: string;
  };
  "dto.VideoProgressRequest": {
    completado?: boolean;
    lastPositionS?: number;
  };
  "dto.VideoResponse": {
    completado?: boolean;
    createdAt?: string;
    descripcion?: string;
    duracionS?: number;
    id?: string;
    materiales?: definitions["dto.MaterialResponse"][];
    orden?: number;
    proveedor?: string;
    sectionId?: string;
    titulo?: string;
    url?: string;
  };
  "dto.VideoUpdateRequest": {
    descripcion?: string;
    duracionS?: number;
    /** @enum {string} */
    proveedor?: "youtube" | "vimeo";
    titulo?: string;
    url?: string;
  };
  "httperr.Error": {
    code?: string;
    details?: { [key: string]: string };
    message?: string;
  };
}

export interface operations {}

export interface external {}
