-- Migration: 0001_init
-- Description: Initial schema for SkillMaker.
--   Creates tables: "user", role, user_role, refresh_token.
--   "user" is quoted because it is a reserved word in PostgreSQL.
--   Soft-delete pattern: activo flag on "user", revoked_at on refresh_token.
--   UUIDs are generated by gen_random_uuid() from pgcrypto.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ===== users module =====

CREATE TABLE "user" (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    google_sub  text        NOT NULL UNIQUE,
    email       text        NOT NULL UNIQUE,
    nombre      text        NOT NULL,
    activo      boolean     NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE role (
    id     bigserial PRIMARY KEY,
    nombre text      NOT NULL UNIQUE
        CHECK (nombre IN ('alumno', 'creador', 'supervisor', 'administrador'))
);

CREATE TABLE user_role (
    user_id     uuid    NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    role_id     bigint  NOT NULL REFERENCES role(id)   ON DELETE RESTRICT,
    asignado_en timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);

-- ===== auth module =====

CREATE TABLE refresh_token (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid        NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    token_hash  text        NOT NULL UNIQUE,
    parent_id   uuid        REFERENCES refresh_token(id) ON DELETE SET NULL,
    expires_at  timestamptz NOT NULL,
    revoked_at  timestamptz,
    used_at     timestamptz,
    user_agent  text,
    ip          inet,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_refresh_token_user_active
    ON refresh_token(user_id) WHERE revoked_at IS NULL;

CREATE INDEX idx_refresh_token_hash
    ON refresh_token(token_hash);
