// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/google": {
            "post": {
                "description": "Valida el ID token de Google, verifica que el campo hd coincida con el\ndominio corporativo configurado (GOOGLE_HOSTED_DOMAIN), crea o actualiza\nel usuario por google_sub y retorna un JWT de acceso + refresh token opaco.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login con Google Workspace",
                "parameters": [
                    {
                        "description": "Google ID token obtenido del cliente",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GoogleLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "body invalido",
                        "schema": {
                            "$ref": "#/definitions/httperr.Error"
                        }
                    },
                    "401": {
                        "description": "token invalido o dominio no autorizado",
                        "schema": {
                            "$ref": "#/definitions/httperr.Error"
                        }
                    },
                    "500": {
                        "description": "error interno",
                        "schema": {
                            "$ref": "#/definitions/httperr.Error"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Revoca el refresh token si existe. Retorna 204 en todos los casos\n(token inexistente, ya revocado, o revocado exitosamente).\nNo requiere JWT en el header.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Revoca el refresh token de la sesion actual (idempotente)",
                "parameters": [
                    {
                        "description": "Refresh token a revocar",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Valida el refresh token presentado, detecta replay attacks (OWASP),\nrevoca el token anterior y emite un par nuevo (access + refresh).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Renueva el access token rotando el refresh token",
                "parameters": [
                    {
                        "description": "Refresh token actual",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "body invalido",
                        "schema": {
                            "$ref": "#/definitions/httperr.Error"
                        }
                    },
                    "401": {
                        "description": "token invalido, expirado o reutilizado",
                        "schema": {
                            "$ref": "#/definitions/httperr.Error"
                        }
                    },
                    "500": {
                        "description": "error interno",
                        "schema": {
                            "$ref": "#/definitions/httperr.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.GoogleLoginRequest": {
            "type": "object",
            "required": [
                "idToken"
            ],
            "properties": {
                "idToken": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserDTO"
                }
            }
        },
        "dto.RefreshRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "dto.UserDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "httperr.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "SkillMaker API",
	Description:      "Plataforma interna de formación en video — LMS corporativo",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
